apiVersion: v1
kind: Pod
metadata:
  name: nfs-pod
spec:
  containers:
    - name: nfs-container
      image: busybox
      command: ["/bin/sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt/nfs
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-pvc

# kubectl exec -it nfs-pod -- sh -c "echo 'Hello K8s NFS' > /mnt/nfs/test.txt"
# cat /nfs/test.txt  # 应输出 "Hello K8s NFS"