services:
  # a9fa84ebf5bf46dcad8fd4ff519195f7
  jenkins:
    image: jenkins/jenkins:jdk21
    restart: always
    user: root
    privileged: true
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/jenkins:/var/jenkins_home
      - /etc/localtime:/etc/localtime:ro
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JAVA_OPTS="-Djenkins.install.runSetupWizard=true -Dsun.jnu.encoding=UTF-8 -Dfile.encoding=UTF-8 -Duser.timezone=Asia/Shanghai"
