apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: user-service
  template:
    metadata:
      labels:
        name: user-service
    spec:
      containers:  # 定义user容器,开放9527端口
        - name: user
            image: 192.168.99.124/k8s-dev/user
            ports:
              - containerPort: 10086
            imagePullPolicy: IfNotPresent
        - name: mysql                     #定义MySQL容器，3306
          image: 192.168.99.124/k8s-dev/mysql-for-user
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
          imagePullPolicy: IfNotPresent
        - name: redis                     #定义Redis容器，开放6379端口
          image: redis:5.0
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]
          ports:
            - containerPort: 6379
          imagePullPolicy: IfNotPresent

