apiVersion: v1
kind: Pod
metadata:
  name: user-service
  labels:
    name: user-service
spec:
  containers:   # 定义user容器信息
    - name: user
      image: 192.168.99.124/k8s-dev/user
      ports:
        - containerPort: 9527
      imagePullPolicy: IfNotPresent
    - name: mysql # 定义mysql容器信息
      image: 192.168.99.124/k8s-dev/mysql-for-user
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
      imagePullPolicy: IfNotPresent
    - name: redis  # 定义redis容器信息
      image: 'redis:5.0'
      lifecycle:
        postStart:
          exec:
            command: [ "/bin/sh", "-c", "redis-cli config set requirepass 123456" ]
      ports:
        - containerPort: 6379
      imagePullPolicy: IfNotPresent
