# 应用名称
appName: "crontab-salve"

# 启动服务信息
serves:
  - {"serveName": "salve", "servePort": 8081, "readTimeOut": 5000, "writeTimeOut": 5000}

# etcd配置信息
etcd:
  server:
    endpoints:
      - "127.0.0.1:2379"
    dialTimeout: 5000

# mongodb 配置
mongodb:
  uri: "mongodb://root:123456@127.0.0.1:27017"
  connectionTimeout: 5000

#  log db与collection配置
log:
#  存储的数据库名称
  db: "cron"
#  存储的表名称
  collection: "log"
#  存储的单批次最大值
  insertBatchSize: 200
#  日志批次自动提交的时间间隔(ms)
  autoCommitTimestamp: 1000