apiVersion: v1
kind: Pod
metadata:
  name: register
  labels:
    name: register
spec:
  containers:
    - name: register
      image: registry.cn-hangzhou.aliyuncs.com/luochunyun/register
      ports:
        - containerPort: 9527
      imagePullPolicy: IfNotPresent
      env:
        - name: consulAddr
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: serviceAddr
          valueFrom:
            fieldRef:
              fieldPath: status.podIP